root: true
env:
    browser: true
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:jest/recommended
    - plugin:jest/style
parser: "@typescript-eslint/parser"
parserOptions:
    project:     "./tsconfig.json"
    ecmaVersion: "latest"
    sourceType:  "module"
