root: true
env:
    browser: true
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:jest/recommended
    - plugin:jest/style
    - plugin:testing-library/react
    - plugin:sonarjs/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    project:     "./tsconfig.json"
    ecmaVersion: "latest"
    sourceType:  "module"
rules:
    react/react-in-jsx-scope: 'off'
    indent: ["error",2]
    comma-spacing: [2, {"before": false, "after": true}]
    camelcase: [2]
    computed-property-spacing: [2, "never"]
    eol-last: 2
    no-mixed-spaces-and-tabs: 2
    no-multiple-empty-lines: [2, {max: 2}]
    no-trailing-spaces: 2
    space-unary-ops: 2
    space-before-blocks: 2
    semi: [2, "never"]
    quotes: ["error", "double"]