name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write
jobs:
  testing:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
          
      - name: Install Library
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run Test
        run: yarn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.fossaApiKey}}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.fossaApiKey}}
          run-tests: true

  build_storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install Library
        run: yarn install --frozen-lockfile

      - name: build Storybook
        run: yarn build_storybook

      - name: Publish Storybook Page
        uses: buberdds/wrangler-action@2.0.0
        id: publish
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish --project-name=scpredict-storybook storybook_dist
      
      - name: Preview Storybook Pages
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview_storybook_pages
          message: |
            # Preview Storybook Page
            ${{ steps.publish.outputs.url }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install Library
        run: yarn install --frozen-lockfile

      - name: Build Page
        run: yarn build
      
      - name: Publish Page
        uses: buberdds/wrangler-action@2.0.0
        id: publish
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish --project-name=scpredict packages/ui/dist
          
      - name: Preview Pages
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview_pages
          message: |
            # Preview Page
            ${{ steps.publish.outputs.url }}
