name: recreate dependabot 
on:
  pull_request:
    types:
      - synchronize

jobs:
  recreate_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR created by Dependabot
        id: dependabot-check
        run: |
          if [ "$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)" == "dependabot[bot]" ]; then
            echo "dependabot=true" >> $GITHUB_OUTPUT
          else
            echo "dependabot=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR sync
        if: steps.dependabot-check.outputs.dependabot == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
          run:
            gh pr comment -b '@dependabot recreate' "${URL}"
