name: recreate dependabot 
on:
  pull_request:
    types:
      - synchronize

jobs:
  recreate_comment:
    runs-on: ubuntu-latest
    if: 
    steps:
      - name: Check if PR created by Dependabot
        id: dependabot-check
        run: |
          if [ "$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)" == "dependabot[bot]" ]; then
            echo "dependabot=true" >> $GITHUB_OUTPUT
          else
            echo "dependabot=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR sync
        if: steps.dependabot-check.outputs.dependabot == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.CREDENTIAL_FOR_UPDATE }}
          script: |
            const comment = '@dependabot recreate';
            const { owner, repo, number } = context.issue;

            github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: number,
              body: comment
            });