name: recreate dependabot 
on:
  pull_request:
    types:
      - synchronize

jobs:
  recreate_comment:
    name: recreate Dependabot PR
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Comment on PR sync
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.CREDENTIAL_FOR_UPDATE }}
          script: |
            const comment = '@dependabot recreate';
            const { owner, repo, number } = context.issue;

            github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: number,
              body: comment
            });
